name: 'GitHub Mirror'

on: [ push, delete, create ]

jobs:
  mirror_to_gitee:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Mirror to gitee'
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_KEY }}
        with:
          source-repo: git@github.com:ZhuYanzhen1/miniFOC.git
          destination-repo: git@gitee.com:zhuyanzhen1/mini-foc.git
